In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 833.0 kB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
from google_play_scraper import reviews, Sort
import pandas as pd

result, _ = reviews(
    'com.gojek.app',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=10000
)

df = pd.DataFrame(result)
df = df[['userName', 'content', 'score']]
df.columns = ['username', 'review', 'rating']
df.to_csv('dataset_gojek.csv', index=False)
print(f"Total data: {len(df)}")
df.head()

Total data: 10000

          username                                             review  rating
0  Pengguna Google                                    sangat membantu       5
1  Pengguna Google         Sangat membantu,cepat dan ramah driver nya       5
2  Pengguna Google  saldo multi trip saya ga masuk masuk, keterang...       1
3  Pengguna Google                                               👍👍👍👍       5
4  Pengguna Google  okee banget aplikasinya, mantulll tapi sayang ...       5

In [ ]:
# Labeling berdasarkan rating
def label_sentiment(rating):
    if rating <= 2:
        return 'negatif'
    elif rating == 3:
        return 'netral'
    else:
        return 'positif'

df['sentiment'] = df['rating'].apply(label_sentiment)

# Cek distribusi label
print(df['sentiment'].value_counts())
print(f"\nTotal data: {len(df)}")
df.head()

sentiment
positif    7039
negatif    2584
netral      377
Name: count, dtype: int64

Total data: 10000

,username,review,rating,sentiment
0,Pengguna Google,sangat membantu,5,positif
1,Pengguna Google,"Sangat membantu,cepat dan ramah driver nya",5,positif
2,Pengguna Google,"saldo multi trip saya ga masuk masuk, keterang...",1,negatif
3,Pengguna Google,👍👍👍👍,5,positif
4,Pengguna Google,"okee banget aplikasinya, mantulll tapi sayang ...",5,positif

In [ ]:
# Simpan dataset dengan label
df.to_csv('dataset_gojek.csv', index=False)
print("Dataset berhasil disimpan!")
print(df['sentiment'].value_counts())

Dataset berhasil disimpan!
sentiment
positif    7039
negatif    2584
netral      377
Name: count, dtype: int64